CREATE TABLE WHOLESALE(CUSTOMERS VARCHAR(100), ITEM VARCHAR(100), COST INT, QUANTITY INT, BILL VARCHAR(100), PRIMARY KEY(COST, BILL))
CREATE TABLE RETAIL(CUSTOMERS VARCHAR(100), COST INT, BILL VARCHAR(100), PRIMARY KEY(BILL))
INSERT INTO WHOLESALE(CUSTOMERS, ITEM, COST, QUANTITY, BILL) VALUES('FIXED', 'BUNDLES', 10000, 100, 'PENDING')
SELECT * FROM WHOLESALE
SELECT * FROM RETAIL
INSERT INTO RETAIL(CUSTOMERS, COST, BILL) VALUES('RARE', 300, 'PAID')
INSERT INTO WHOLESALE(CUSTOMERS, ITEM, COST, QUANTITY, BILL) VALUES('REGULAR', 'BUNDLES', 15000, 20, 'HALF-PAYMENT')
INSERT INTO RETAIL(CUSTOMERS, COST, BILL) VALUES('REGULAR', 305, 'HALF-PAYMENT')
INSERT INTO WHOLESALE(customers, item, cost, quantity, bill) VALUES('', 'BUNDLES', 1000, 50, 'PENDING')
SELECT w.CUSTOMERS, w.ITEM, w.COST, w.QUANTITY, w.BILL, r.BILL FROM WHOLESALE w JOIN RETAIL r ON w.COST = r.COST
WHERE w.QUANTITY = 100
SELECT DISTINCT ITEM FROM WHOLESALE
SELECT DISTINCT COST FROM RETAIL
SELECT * FROM WHOLESALE WHERE COST = 10000
SELECT * FROM WHOLESALE WHERE QUANTITY = 100
SELECT * FROM RETAIL WHERE cost = 300
SELECT * FROM WHOLESALE WHERE BILL ='PAID'
SELECT * FROM RETAIL WHERE BILL = 'PENDING'
SELECT COUNT(*) FROM WHOLESALE WHERE COST = 10000
SELECT COUNT(*) FROM RETAIL WHERE COST = 300